nextSqaure함수는 정수 n을 매개변수로 입력받습니다.
n이 임의의 정수 x의 제곱이라면 x+1의 제곱을 리턴하고, n이 임의의 정수 x의 제곱이 아니라면 'no'을 리턴하는 함수를 완성하세요.
예를들어 n이 121이라면 이는 정수 11의 제곱이므로 (11+1)의 제곱인 144를 리턴하고, 3이라면 'no'을 리턴하면 됩니다

In [44]:
def nextSqure(n):
    for i in range(2,n):
        if n == i**2: 
            return (i+1)**2
    return 'no'


In [45]:
print("결과 : {}".format(nextSqure(121)))

결과 : 144


딕셔너리는 들어있는 값에 순서가 없지만, 키를 기준으로 정렬하고 싶습니다. 그래서 키와 값을 튜플로 구성하고, 이를 순서대로 리스트에 넣으려고 합니다.
예를들어 {"김철수":78, "이하나":97, "정진원":88}이 있다면 각각의 키와 값을

("김철수", 78)
("이하나", 97)
("정진원", 88)
과 같이 튜플로 분리하고 키를 기준으로 정렬해서 다음과 같은 리스트를 만들면 됩니다.
[ ("김철수", 78), ("이하나", 97), ("정진원", 88) ]

다음 sort_dictionary 함수를 완성해 보세요.

In [89]:
def sort_dictionary(dic):
    dic.items()
    
    return 

# 아래는 테스트로 출력해 보기 위한 코드입니다.
print( sort_dictionary( {"김철수":78, "이하나":97, "정진원":88} ))

dict_items([('김철수', 78), ('이하나', 97), ('정진원', 88)])


In [108]:
dic = {"김철수":78, "이하나":97, "정진원":88} 
dic1 = dic.items()
sorting = sorted(dic.keys())
sorting

['김철수', '이하나', '정진원']

In [171]:
def number_generator(x, n):
  
    list1=[]
    for i in range(x,x*n+1):
        list1.append(i)
    return list1[x-x:x*n+1:x]



In [172]:
# 아래는 테스트로 출력해 보기 위한 코드입니다.
print(number_generator(3,5))

[3, 6, 9, 12, 15]


In [174]:
## 다른사람 답 
def number_generator(x, n):
    # 함수를 완성하세요
    return [i * x + x for i in range(n)]

In [175]:
print(number_generator(3,5))

[3, 6, 9, 12, 15]


rm_small함수는 list타입 변수 mylist을 매개변수로 입력받습니다.
mylist 에서 가장 작은 수를 제거한 리스트를 리턴하고, mylist의 원소가 1개 이하인 경우는 []를 리턴하는 함수를 완성하세요.
예를들어 mylist가 [4,3,2,1]인 경우는 [4,3,2]를 리턴 하고, [10, 8, 22]면 [10, 22]를 리턴 합니다.

In [218]:
def rm_small(mylist):
    if len(mylist)>1:
        minimum = min(mylist)
        i = mylist.index(minimum)
        del mylist[i]
               
        return mylist
    return []

In [219]:
my_list = [4, 3, 2, 1]
print("결과 {} ".format(rm_small(my_list)))

결과 [4, 3, 2] 


In [ ]:
## 다른사람 결과값 
def rm_small(mylist):
    return [i for i in mylist if i > min(mylist)]

피보나치 수열
피보나치 수는 F(0) = 0, F(1) = 1일 때, 2 이상의 n에 대하여 F(n) = F(n-1) + F(n-2) 가 적용되는 점화식입니다. 2 이상의 n이 입력되었을 때, fibonacci 함수를 제작하여 n번째 피보나치 수를 반환해 주세요. 예를 들어 n = 3이라면 2를 반환해주면 됩니다.

In [243]:
def fibonacci(n):
    fibo =[0,1]
    for i in range(2,n+1):
        fibo.append(fibo[i-1]+fibo[i-2])
        
    return fibo[-1]

In [244]:
fibonacci(49)

7778742049

In [242]:
## 다른사람의 답 
def fibonacci(num):
    a, b = 0, 1
    for i in range(num):
        a, b = b, a+b
    return a

# 아래는 테스트로 출력해 보기 위한 코드입니다.
print(fibonacci(49))

7778742049


getMiddle메소드는 하나의 단어를 입력 받습니다. 단어를 입력 받아서 가운데 글자를 반환하도록 getMiddle메소드를 만들어 보세요. 단어의 길이가 짝수일경우 가운데 두글자를 반환하면 됩니다.
예를들어 입력받은 단어가 power이라면 w를 반환하면 되고, 입력받은 단어가 test라면 es를 반환하면 됩니다.

In [250]:
def string_middle(string):
    target = int(len(string)/2)
    if len(string)% 2 ==0:
        return string[target-1:target+1]
    else: return string[target]

# 아래는 테스트로 출력해 보기 위한 코드입니다.
print(string_middle("abcdefgh"))

de


In [254]:
## 다른사람 답
def string_middle(string):
    return string[(len(string)-1)//2:len(string)//2+1]

# 아래는 테스트로 출력해 보기 위한 코드입니다.
print(string_middle("po345wer"))

45


행렬의 덧셈은 행과 열의 크기가 같은 두 행렬의 같은 행, 같은 열의 값을 서로 더한 결과가 됩니다. 2개의 행렬을 입력받는 sumMatrix 함수를 완성하여 행렬 덧셈의 결과를 반환해 주세요.

예를 들어 2x2 행렬인 A = ((1, 2), (2, 3)), B = ((3, 4), (5, 6)) 가 주어지면, 같은 2x2 행렬인 ((4, 6), (7, 9))를 반환하면 됩니다.(어떠한 행렬에도 대응하는 함수를 완성해주세요.)

In [279]:
def MulMatrix(A,B):
    a = A[0][0]
    b = A[0][1]
    c = A[1][0]
    d = A[1][1]
    e = B[0][0]
    f = B[0][1]
    g = B[1][0]
    h = B[1][1]
    
    return [[a*e+b*g,e*f+b*h],[c*e+d*g,c*f+d*h]]

In [280]:
# 아래는 테스트로 출력해 보기 위한 코드입니다.
print(MulMatrix([[1,2], [2,3]], [[3,4],[5,6]]))

[[13, 24], [21, 26]]


In [282]:
def sumMatrix(A,B):
    a = A[0][0]
    b = A[0][1]
    c = A[1][0]
    d = A[1][1]
    e = B[0][0]
    f = B[0][1]
    g = B[1][0]
    h = B[1][1]
    
    return [[a+e,b+f],[c+g,d+h]]

print(sumMatrix([[1,2], [2,3]], [[3,4],[5,6]]))

[[4, 6], [7, 9]]


evenOrOdd 메소드는 int형 num을 매개변수로 받습니다.
num이 짝수일 경우 "Even"을 반환하고 홀수인 경우 "Odd"를 반환하도록 evenOrOdd에 코드를 작성해 보세요.
num은 0이상의 정수이며, num이 음수인 경우는 없습니다

In [291]:
def everOrOdd(num):
    if num %2 == 0:
        return "Even"
    return "Odd"

In [293]:
def everOrOdd(num):
    return "Even" if num % 2 == 0 else "Odd"

In [292]:
## 다른사람답
def evenOrOdd(num):
    return num % 2 and "Odd" or "Even"
## num % 2 가 0인경우 False에 해당하므로 and랑 걸려있는 "Odd"는 실행되지 않음 > or 에 걸려있는 "Even 
## 

'Odd'

In [302]:
False and "odd"

False

In [304]:
True and "Odd" ## 인경우 "Odd" 뒷조건은 보지 않고 "Odd" 반환 

'Odd'

In [305]:
False or "Even"

'Even'

In [334]:
def alpha_string46(s):
    if len(s)==4 or len(s)==6:
        for i in s: 
            if i in 'abcdefghijklmnopqrstuvwxyz':
                return False 
            return True


In [335]:
alpha_string46('46l6')

True

sum_digit함수는 자연수를 전달 받아서 숫자의 각 자릿수의 합을 구해서 return합니다.
예를들어 number = 123이면 1 + 2 + 3 = 6을 return하면 됩니다.
sum_digit함수를 완성해보세요.

In [385]:
def sum_digits(n):
    s = 0
    while n:
        s = n % 10 + s ## 나머지
        n =n//10 ## 몫
    return s

In [386]:
n = 1234
sum_digits(n)

10

In [388]:
divmod(16,4) ## 나누기 함수 
## input a, b 
## output a//b, a%b

(4, 0)

In [391]:
## 다른사람 정답 
def sum_digit(number):
    if number < 10:
        return number;
    return (number % 10) + sum_digit(number // 10) 

In [399]:
def sum_digit(number):
    return sum(map(int,str(number)))

딕셔너리는 들어있는 값에 순서가 없지만, 키를 기준으로 정렬하고 싶습니다. 그래서 키와 값을 튜플로 구성하고, 이를 순서대로 리스트에 넣으려고 합니다.
예를들어 {"김철수":78, "이하나":97, "정진원":88}이 있다면 각각의 키와 값을

("김철수", 78)
("이하나", 97)
("정진원", 88)
과 같이 튜플로 분리하고 키를 기준으로 정렬해서 다음과 같은 리스트를 만들면 됩니다.
[ ("김철수", 78), ("이하나", 97), ("정진원", 88) ]

다음 sort_dictionary 함수를 완성해 보세요.

In [ ]:
def sort_dictionary(dic):
    return sorted(dic.items(), key=lambda x: x[0])

# 아래는 테스트로 출력해 보기 위한 코드입니다.
print( sort_dictionary( {"김철수":78, "이하나":97, "정진원":88} ))

In [405]:
dict1 = {"김철수":78, "이하나":97, "정진원":88}
dict.items(dict1)

dict_items([('김철수', 78), ('이하나', 97), ('정진원', 88)])

strange_sort함수는 strings와 n이라는 매개변수를 받아들입니다.
strings는 문자열로 구성된 리스트인데, 각 문자열을 인덱스 n인 글자를 기준으로 정렬하면 됩니다.

예를들어 strings가 ["sun", "bed", "car"]이고 n이 1이면 각 단어의 인덱스 1인 문자 u, e ,a를 기준으로 정렬해야 하므로 결과는 ["car", "bed", "sun"]이 됩니다.
strange_sort함수를 완성해 보세요.

In [ ]:
def strange_sort(strings, n): 
    '''strings의 문자열들을 n번째 글자를 기준으로 정렬해서 return하세요'''
    return sorted(strings, key = lambda x : x[n])



# 아래는 테스트로 출력해 보기 위한 코드입니다.
print( strange_sort(["sun", "bed", "car"], 1) )

별이는 헬로월드텔레콤에서 고지서를 보내는 일을 하고 있습니다. 개인정보 보호를 위해 고객들의 전화번호는 맨 뒷자리 4자리를 제외한 나머지를 "*"으로 바꿔야 합니다.
전화번호를 문자열 s로 입력받는 hide_numbers함수를 완성해 별이를 도와주세요
예를들어 s가 "01033334444"면 "*******4444"를 리턴하고, "027778888"인 경우는 "*****8888"을 리턴하면 됩니다.

In [414]:
s = '010283945789384'
def hide_number(s):
    return '*'*(len(s)-4)+s[-4:]


In [415]:
hide_number(s)

'***********9384'

In [ ]:
## 다른사람 답
import re

def hide_numbers(s):
    p = re.compile(r'\d(?=\d{4})')
    return p.sub("*", s, count = 0)

findKim 함수(메소드)는 String형 배열 seoul을 매개변수로 받습니다.

seoul의 element중 "Kim"의 위치 x를 찾아, "김서방은 x에 있다"는 String을 반환하세요.
seoul에 "Kim"은 오직 한 번만 나타나며 잘못된 값이 입력되는 경우는 없습니다.

In [419]:
def findKim(seoul):
    for i in range(len(seoul)):
        if seoul[i]=="Kim":
            return "김서방은 {}에 있다".format(i)


# 실행을 위한 테스트코드입니다.
print(findKim(["Queen", "Tod", "Kim"]))

김서방은 2에 있다


In [421]:
def findKim(seoul):
    return "김서방은 {}에 있다".format(seoul.index('Kim'))
print(findKim(["Queen", "Tod", "Kim"]))

김서방은 2에 있다


no_continuous함수는 스트링 s를 매개변수로 입력받습니다.

s의 글자들의 순서를 유지하면서, 글자들 중 연속적으로 나타나는 아이템은 제거된 배열(파이썬은 list)을 리턴하도록 함수를 완성하세요.
예를들어 다음과 같이 동작하면 됩니다.

s가 '133303'이라면 ['1', '3', '0', '3']를 리턴
s가 '47330'이라면 [4, 7, 3, 0]을 리턴

In [462]:
def no_continuous(s):
    for i in range(len(s)):
        n = []
        if s[i] != s[i+1:i+2]:
            n.append(s[i])
        
        return n

# 아래는 테스트로 출력해 보기 위한 코드입니다.
print( no_continuous( "133303" ))

['1']


In [460]:
def no_continuous(s):
    return [s[i] for i in range(len(s)) if s[i] != s[i+1:i+2]]
print( no_continuous( "133303" ))

['1', '3', '0', '3']


In [ ]:
def no_continuous(s):
    a = []
    for i in s:
        if a[-1:] == [i]: continue
        a.append(i)
    return a

2016년 1월 1일은 금요일입니다. 2016년 A월 B일은 무슨 요일일까요? 두 수 A,B를 입력받아 A월 B일이 무슨 요일인지 출력하는 getDayName 함수를 완성하세요. 요일의 이름은 일요일부터 토요일까지 각각

SUN,MON,TUE,WED,THU,FRI,SAT

를 출력해주면 됩니다. 예를 들어 A=5, B=24가 입력된다면 5월 24일은 화요일이므로 TUE를 반환하면 됩니다.

In [478]:
from datetime import datetime
def getDayName(a,b):

    weekdays = ['MON','TUE','WED','THU','FRI','SAT','SUN']
    i = datetime(2016,a,b).weekday()
    return weekdays[i]

In [479]:
getDayName(3,14)

'MON'

In [494]:
def printTriangle(num):
    s =''
    for i in range(num):
        s += '*'*(i+1)+'\n'
    return s

In [496]:
print(printTriangle(4))

*
**
***
****



In [497]:
## 다른사람 답
def printTriangle(num):
    return ''.join(['*'*i + '\n' for i in range(1,num+1)])
print(printTriangle(4))

In [509]:
''.join('...')
''.join(['1,2,3,4,5']) ## string만 가능 
print(''.join(['*\n**\n***\n****\n']))

*
**
***
****



In [510]:
def numPY(s):

    return s.lower().count('p')==s.lower().count('y')

# 아래는 테스트로 출력해 보기 위한 코드입니다.
print( numPY("pPoooyY") )
print( numPY("Pyy") )

True
False


In [ ]:
소수 찾기 

In [515]:
def prime(n):
    for i in range(2,n):
        if n % i == 0: return False 
            
        return True

In [516]:
prime(345)

True

In [519]:
def sumDivisor(num):
    div =[]
    for i in range(1,num+1):
        if num % i ==0:
              div.append(i)
    return sum(div)

In [521]:
sumDivisor(12)

28

In [522]:
## 다른사람 답 
def sumDivisor(num):
    # num / 2 의 수들만 검사하면 성능 약 2배 향상잼
    return num + sum([i for i in range(1, (num // 2) + 1) if num % i == 0])

In [535]:
a = np.array([[1,6],[2,7],[3,8],[4,9],[5,10]])
print(np.stack(a, axis = 0))
print(np.stack(a, axis = 1))## Transpose 한것처럼 쌓아줌  
print(a.T)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [549]:
s = '344565'
s.isdigit()

True

In [550]:
def alpha_string46(s):
    return s.isdigit() and (len(s)==4 or len(s)==6)
alpha_string46(s)

In [ ]:
## 다른사람 풀이
def alpha_string46(s):
    return s.isdigit() and len(s) in [4, 6]

In [3]:
def water_melon(n):
    s = "수박" * n
    return s[:n]


# 실행을 위한 테스트코드입니다.
print("n이 13인 경우: " + water_melon(13));
print("n이 4인 경우: " + water_melon(4));


n이 13인 경우: 수박수박수박수박수박수박수
n이 4인 경우: 수박수박


In [4]:
def sumMatrix(A,B):
    answer = [[c + d for c, d in zip(a, b)] for a, b in zip(A,B)]
    return answer


In [5]:
A = [[1,2],[3,4]]
B = [[5,6],[7,8]]
sumMatrix(A,B)

[[6, 8], [10, 12]]

In [12]:
for a,b in zip(A,B):
    for c,d in zip(a,b):
        print(c,d)

1 5
2 6
3 7
4 8


In [13]:
def sumMatrix(A,B):
    answer = [[] for j in range(len(A))]  
    for i in range(len(A)):
        for x in range(len(A[i])):
            answer[i].append(A[i][x] + B[i][x])
    return answer

# 아래는 테스트로 출력해 보기 위한 코드입니다.
print(sumMatrix([[1,2], [2,3]], [[3,4],[5,6]]))

[[4, 6], [7, 9]]


In [21]:
numbers2 = []
for i in range(3,5+1):
    numbers2.append(i)
print(sum(numbers2))

12


In [27]:
from functools import reduce
list1 = [3,4,5]
print(reduce(lambda x, y: x+y ,list1 ))

12


adder함수는 정수 a, b를 매개변수로 입력받습니다.
두 수와 두 수 사이에 있는 모든 정수를 더해서 리턴하도록 함수를 완성하세요. a와 b가 같은 경우는 둘 중 아무 수나 리턴하세요.
예를들어 a가 3, b가 5이면 12를 리턴하면 됩니다.

a, b는 음수나 0, 양수일 수 있으며 둘의 대소 관계도 정해져 있지 않습니다.

In [40]:
def adder(a,b):
    if a == b: return a
    elif a>b: return sum([i for i in range(b,a+1)])
    else: return sum([i for i in range(a,b+1)])
    

In [45]:
adder(-6,3)

-15

In [ ]:
## 다른사람 풀이 
def adder(a, b):
    # 함수를 완성하세요
    if a > b: a, b = b, a

    return sum(range(a,b+1))

In [44]:
## 다른사람 풀이 
def adder(a, b):
    return sum([i for i in range(min(a,b),max(a,b)+1)])
    
adder(6,3)  

18

In [63]:
def is_pair(s):
    if s[0]=='(' and (s.count('(')==s.count(')') ):return True
    elif s[-1]=='(': return False

In [64]:
print( is_pair("(hello)()"))
print( is_pair(")("))

True
False


In [ ]:
def longest_palindrom(s):
    
    return 0


# 아래는 테스트로 출력해 보기 위한 코드입니다.
print(longest_palindrom("토마토맛토마토"))
print(longest_palindrom("토마토맛있어"))